### ISSUE TITLE
ValueError: New Mach-O header is too large to relocate...

### ISSUE THREAD

**Issue by stephenhouser** [stephenhouser/k40-whisperer#1]
Building generates a bunch of Mach-O relocation errors. The application still *appears* to work properly, but these bug me and should be resolved.

```
...
WARNING: Mach-O header in '/Users/houser/Projects/K40_Whisperer/dist/K40 Whisperer.app/Contents/Resources/lib/python3.7/PIL/.dylibs/liblcms2.2.dylib' may be too large to relocate
locate /usr/lib/libSystem.B.dylib None -> /usr/lib/libSystem.B.dylib
Traceback (most recent call last):
  File "py2app_setup.py", line 51, in <module>
    **extra_options
  File "/Users/houser/Projects/K40_Whisperer/python_venv/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/Users/houser/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/houser/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/houser/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/houser/Projects/K40_Whisperer/.eggs/py2app-0.18-py3.7.egg/py2app/build_app.py", line 838, in run
    self._run()
  File "/Users/houser/Projects/K40_Whisperer/.eggs/py2app-0.18-py3.7.egg/py2app/build_app.py", line 1053, in _run
    self.run_normal()
  File "/Users/houser/Projects/K40_Whisperer/.eggs/py2app-0.18-py3.7.egg/py2app/build_app.py", line 1165, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/houser/Projects/K40_Whisperer/.eggs/py2app-0.18-py3.7.egg/py2app/build_app.py", line 1525, in create_binaries
    platfiles = mm.run()
  File "/Users/houser/Projects/K40_Whisperer/.eggs/macholib-1.11-py3.7.egg/macholib/MachOStandalone.py", line 162, in run
    node.write(f)
  File "/Users/houser/Projects/K40_Whisperer/.eggs/macholib-1.11-py3.7.egg/macholib/MachO.py", line 153, in write
    header.write(f)
  File "/Users/houser/Projects/K40_Whisperer/.eggs/macholib-1.11-py3.7.egg/macholib/MachO.py", line 368, in write
    self.synchronize_size()
  File "/Users/houser/Projects/K40_Whisperer/.eggs/macholib-1.11-py3.7.egg/macholib/MachO.py", line 358, in synchronize_size
    self.low_offset, self.sizediff))
ValueError: New Mach-O header is too large to relocate in '/Users/houser/Projects/K40_Whisperer/dist/K40 Whisperer.app/Contents/Resources/lib/python3.7/PIL/.dylibs/liblcms2.2.dylib' (new size=1688, max size=1680, delta=48)
```

The solutions I have found all focus around installing the Python libraries in a *very deep path* so that the strings in the dynamic libraries can be rewritten in-place. I've not tried this yet, `pyenv` is just too easy :-)

**Comment by stephenhouser** [comment]
This error goes away with the PyInstaller packaging. Will remain unresolved and not be resolved until that becomes the primary packaging method.

**Comment by stephenhouser** [comment]
Closing as I move the the pyinstaller packaging system and this is not a problem there.
